### ISSUE TITLE
problem in demo code

### ISSUE THREAD

**Issue by zhblinder** [BehindTheMath/KosherZmanim#16]
Hi,

In the demo code you use parseInt for latitude, longitude & elevation, so for locations not on exact degrees it's impossible to get right zmanim!

Zvika

**Comment by BehindTheMath** [comment]
Good point, thank you.

Fixed by 3828c23.

**Comment by zhblinder** [comment]
Thanks a lot! Now it provide the same results as other programs I use in different circumstances for zmanim computations. :)

Thanks again for all your efforts and especially for quick fix of this issue.

Zvika
