### ISSUE TITLE
why Timezone ID & Location Name are mandatory ?

### ISSUE THREAD

**Issue by Danielg212** [BehindTheMath/KosherZmanim#6]
Latitude and Longitude are not enough?

**Comment by BehindTheMath** [comment]
Location name can probably be made optional.

Timezone ID is required because it needs to know which timezone to return times for. I don't know of a way to return a timezone ID from coordinates that wouldn't require a network call.

**Comment by BehindTheMath** [comment]
Fixed by 415e0de68e689962be9031942fde1a7d78669c67.
