### ISSUE TITLE
Bug in getMoladAsDate - JewishCalendar - Jerusalem Time Zone

### ISSUE THREAD

**Issue by er11cohen** [BehindTheMath/KosherZmanim#9]
The time zone need to be "Etc/GMT+2" now is "Etc/GMT-2".
The line is:
 var yerushalayimStandardTZ = "Etc/GMT-2";
Thank you ver much.

**Comment by shalomscott** [comment]
I made a PR for this. Checkout #10

**Comment by BehindTheMath** [comment]
Closed by #10 .
